name = "scientia-capital"
compatibility_date = "2024-01-01"

# D1 Database binding (when you create it)
# [[d1_databases]]
# binding = "DB"
# database_name = "scientia-capital-db"
# database_id = "your-database-id"

# Environment variables (set these in Cloudflare dashboard)
[vars]
JWT_SECRET = "your-super-secret-jwt-key-minimum-32-chars"
JWT_EXPIRES_IN = "7d"
REFRESH_TOKEN_EXPIRES_IN = "30d"
BCRYPT_ROUNDS = "10"

# KV namespace for session storage (when you create it)
# [[kv_namespaces]]
# binding = "SESSIONS"
# id = "your-kv-namespace-id"