#!/bin/bash

# API Integration Specialist - Specialized Context Loading Script
# Loads API documentation, rate limits, and integration patterns

echo "🔌 API INTEGRATION SPECIALIST - Loading API context..."
echo "===================================================="

PROJECT_ROOT="/Users/tmk/Documents/prophet-growth-analysis"

# Phase 1: API Architecture Overview
echo "🏗️ Phase 1: API Architecture Context..."
echo ""
echo "✅ Current API Stack:"
echo "   → Next.js 15 App Router API Routes"
echo "   → RESTful design patterns"
echo "   → Zod schema validation"
echo "   → TypeScript end-to-end type safety"
echo "   → Direct API integrations (no complex orchestration)"
echo ""

# Phase 2: External API Integrations
echo "🌐 Phase 2: External APIs Configuration..."
echo ""
echo "✅ Anthropic Claude API:"
echo "   → Model: claude-3-5-sonnet-20241022"
echo "   → Rate Limits: 50 requests/minute"
echo "   → Max tokens: 4096 per request"
echo "   → Streaming support available"
echo "   → Context window: 200K tokens"
echo ""
echo "✅ ElevenLabs Voice API:"
echo "   → Voice synthesis endpoint"
echo "   → Multiple voice options"
echo "   → Audio format: MP3/WAV"
echo "   → Streaming audio support"
echo "   → SSML markup supported"
echo ""

# Phase 3: API Route Structure
echo "📁 Phase 3: API Routes Organization..."
echo ""
echo "✅ Current API Endpoints:"
echo "   → /api/auth/* - Authentication endpoints"
echo "   → /api/chat - Claude AI integration"
echo "   → /api/voice - ElevenLabs synthesis"
echo "   → /api/analyze - Financial analysis"
echo "   → /api/forecast - Prophet predictions"
echo "   → /api/employees - Employee management"
echo ""

# Phase 4: Request/Response Patterns
echo "📨 Phase 4: API Design Patterns..."
echo ""
echo "✅ Request Validation:"
echo "   → Use Zod schemas for all inputs"
echo "   → TypeScript types from schemas"
echo "   → Consistent error responses"
echo "   → Request body size limits"
echo ""
echo "✅ Response Standards:"
echo "   → Consistent JSON structure"
echo "   → Proper HTTP status codes"
echo "   → Error handling with details"
echo "   → Pagination for lists"
echo ""

# Phase 5: Authentication Patterns
echo "🔐 Phase 5: API Authentication..."
echo ""
echo "✅ Auth Implementation:"
echo "   → JWT tokens in Authorization header"
echo "   → Bearer token format"
echo "   → Token refresh endpoints"
echo "   → API key management for services"
echo ""

# Phase 6: Rate Limiting Strategy
echo "⚡ Phase 6: Rate Limiting Configuration..."
echo ""
echo "✅ Rate Limit Tiers:"
echo "   → Public endpoints: 20 req/min"
echo "   → Authenticated: 100 req/min"
echo "   → AI endpoints: 50 req/min"
echo "   → Implement exponential backoff"
echo "   → Return rate limit headers"
echo ""

# Phase 7: Error Handling Patterns
echo "❗ Phase 7: Error Handling Standards..."
echo ""
echo "✅ Error Response Format:"
echo "```json"
echo "{"
echo "  \"error\": {"
echo "    \"code\": \"VALIDATION_ERROR\","
echo "    \"message\": \"Invalid input data\","
echo "    \"details\": {}"
echo "  }"
echo "}"
echo "```"
echo ""
echo "✅ Common Error Codes:"
echo "   → 400 - Bad Request (validation)"
echo "   → 401 - Unauthorized"
echo "   → 403 - Forbidden"
echo "   → 404 - Not Found"
echo "   → 429 - Rate Limited"
echo "   → 500 - Server Error"
echo ""

# Phase 8: API Testing Tools
echo "🧪 Phase 8: API Testing Context..."
echo ""
echo "✅ Testing Commands:"
echo "   → curl - Quick endpoint tests"
echo "   → httpie - User-friendly HTTP client"
echo "   → Postman - Comprehensive testing"
echo "   → Jest - Automated API tests"
echo ""

# Phase 9: Performance Optimization
echo "🚀 Phase 9: API Performance Tips..."
echo ""
echo "✅ Optimization Strategies:"
echo "   → Response caching with proper headers"
echo "   → Database connection pooling"
echo "   → Async/await for all operations"
echo "   → Minimize payload sizes"
echo "   → Use streaming for large responses"
echo ""

# Context Summary
echo "🎯 API INTEGRATION SPECIALIST CONTEXT LOADED"
echo "===================================================="
echo "✅ API Architecture: Understood"
echo "✅ External APIs: Configured"
echo "✅ Rate Limits: Known"
echo "✅ Error Patterns: Standardized"
echo "✅ Ready to build robust API integrations!"
echo "===================================================="